spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ecs.016imcn.love:3306/well-matched-team?serverTimezone=UTC
    username: 016
    password: 'MySql@016016'
  redis:
    host: 119.23.49.102
    port: 9810
    password: '016016'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  servlet:
    multipart:
      max-file-size: 512MB
      enabled: true
      max-request-size: -1
      resolve-lazily: true