spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ecs.016imcn.love:3306/well-matched-team?serverTimezone=UTC
    username: '016'
    password: 'MySql@016016'

  servlet:
    multipart:
      max-file-size: 512MB
      enabled: true
      max-request-size: -1
      resolve-lazily: true